window.FULL_BIBLIOGRAPHY = [
  "Ajotikar, Rasika. \"Marathi Sangeet Natak and the Affirmation of Hindu Nationalist Cultural Politics in Western India.\" The World of Music 10, no. 1 (2021): 105-30. http://www.jstor.org/stable/27032508.\\",
  "Ajotikar, Rasika. \"'Our Song Impure, Our Voice Polluted': Conversations with Activist and Musician Shital Sathe.\" Feminist Review (London, United Kingdom) 119, no. 1 (2018): 154-62. http://dx.doi.org.ezp.lib.rochester.edu/10.1057/s41305-018-0111-1.\\",
  "Alaghband-Zadeh, Chlo\\'eb. \"Listening to North Indian Classical Music: How Embodied Ways of Listening Perform Imagined Histories and Social Class.\" Ethnomusicology 61, no. 2 (2017): 207-33. JSTOR. https://doi.org/10.5406/ethnomusicology.61.2.0207.\\",
  "Allen, Matthew Harp. \"Rewriting the Script for South Indian Dance.\" TDR (1988-) 41, no. 3 (1997): 63-100. https://doi.org/10.2307/1146609.\\",
  "Alonso, Isabel Huacuja. \"Radio, Citizenship, and the 'Sound Standards' of a Newly Independent India.\" Public Culture 31, no. 1 (2019): 117-44. https://doi.org/10.1215/08992363-7181862.\\",
  "Anna Stirr. \"'May I Elope': Song Words, Social Status, and Honor among Female Nepali Dohori Singers.\" Ethnomusicology 54, no. 2 (2010): 257. https://doi.org/10.5406/ethnomusicology.54.2.0257.\\",
  "Avanti, Peter. \"Black Musics, Technology, and Modernity: Exhibit A, the Drum Kit.\" Popular Music and Society 36, no. 4 (2013): 476-504. https://doi.org/10.1080/03007766.2012.681111.\\",
  "Ayyagari, Shalini. \"Spaces Betwixt and Between: Musical Borderlands and the Manganiyar Musicians of Rajasthan.\" Asian Music 43, no. 1 (2012): 3-33. https://muse.jhu.edu/article/461558/summary.\\",
  "Beaster-Jones, Jayson. \"Evergreens to Remixes: Hindi Film Songs and India's Popular Music Heritage.\" Ethnomusicology 53, no. 3 (2009): 425-48. http://www.jstor.org/stable/25653086.\\",
  "Bedford, Ian. \"Listening to the Voice in South Indian Classical Music.\" TAJA The Australian Journal of Anthropology 19, no. 2 (2008): 237-44.\\",
  "Bennett, Andrew. \"Bhangra in Newcastle: Music, Ethnic Identity and the Role of Local Knowledge.\" Innovation: The European Journal of Social Science Research 10, no. 1 (1997): 107-16.\\",
  "Bhaumik, Kaushik. \"A Brief History of Cinema from Bombay to 'Bollywood.'\" HIC3 History Compass 2, no. 1 (2004): **.\\",
  "Bond, Brian E. \"Teaching Islam in Song: Storytelling and Islamic Meaning in Sindhi Sufi Poetry Performance.\" Asian Music 51, no. 2 (2020): 39-71. https://doi.org/10.1353/amu.2020.0019.\\",
  "Booth, Gregory. \"Copyright Law and the Changing Economic Value of Popular Music in India.\" Ethnomusicology 59, no. 2 (2015): 262-87. https://doi.org/10.5406/ethnomusicology.59.2.0262.\\",
  "Booth, Gregory D. \"Brass Bands: Tradition, Change, and the Mass Media in Indian Wedding Music.\" Ethnomusicology 34, no. 2 (1990): 245. https://doi.org/10.2307/851685.\\",
  "Booth, Gregory D. \"Making a Woman from a Tawaif: Courtesans as Heroes in Hindi Cinema.\" New Zealand Journal of Asian Studies 9, no. 2 (2007): 1.\\",
  "Bor, Joep. \"The Rise of Ethnomusicology: Sources on Indian Music c.1780 - c.1890.\" Yearbook for Traditional Music 20 (January 1988): 51-73. https://doi.org/10.2307/768166.\\",
  "Brown, Katherine. \"Reading Indian Music: The Interpretation of Seventeenthcentury European Travelwriting in the (Re)Construction of Indian Music History.\" British Journal of Ethnomusicology 9, no. 2 (2000): 1-34.\\",
  "CAPWELL, CHARLES. The Popular Expression of Religious Syncretism: The Bauls of Bengal as Apostles Of. n.d. Accessed August 17, 2017. http://www.jstor.org/stable/pdf/853531.pdf.\\",
  "Chakravorty, Pallabi. \"Moved to Dance: Remix, Rasa , and a New India.\" Visual Anthropology 22, nos. 2-3 (2009): 211-28. https://doi.org/10.1080/08949460902748113.\\",
  "Clayton, Martin. \"Ethnographic Wax Cylinders at the British Library National Sound Archive: A Brief History and Description of the Collection.\" British Journal of Ethnomusicology 5 (1996): 67.\\",
  "Clayton, Martin. Introduction: Towards a Theory of Musical Meaning (in India and Elsewhere). 2001. http://www.tandfonline.com/doi/abs/10.1080/09681220108567307.\\",
  "Clayton, Martin. \"Theory and Practice of Long-Form Non-Isochronous Meters: The Case of the North Indian Rpak Tl.\" Music Theory Online 26, no. 1 (2020): 2.\\",
  "Davis, Coralynn. \"Im Possible Lives: Gender, Class, Self-Fashioning, and Affinal Solidarity in Modern South Asia.\" Social Identities 15, no. 2 (2009): 243-72. https://doi.org/10.1080/13504630902778701.\\",
  "Desai-Stephens, Anaar. \"The Age of Aspiration? Music Classes and the Limits of Gendered Self-Transformation in Mumbai.\" MUSICultures 44, no. 1 (2018): 1. https://journals.lib.unb.ca/index.php/MC/article/view/26079.\\",
  "Desai-Stephens, Anaar. \"The Infrastructure of Engagement: Musical Aesthetics and the Rise of YouTube in India.\" Twentieth-Century Music 19, no. 3 (2022): 444-71. https://doi.org/10.1017/S1478572222000299.\\",
  "Desai-Stephens, Anaar. \"'You Have to Feel to Sing!': Popular Music Classes and the Transmission of 'Feel' in Contemporary India.\" Culture, Theory and Critique, January 13, 2021, 1-21. https://doi.org/10.1080/14735784.2020.1861954.\\",
  "Dikshitar, Subbarama. \"Sangita Sampradaya Pradarsini.\" English Translation Available at Http://Www. Ibiblio. Org/Guruguha/Ssp. Htm, 1904.\\",
  "Dinnerstein, Noe. HIMALAYA, the Journal of Th e Association for Nepal an d Himalayan Studies. 2018.\\",
  "Du Perron, Lalita. : \": A Discussion of the Female Voice of Hindustani Music.\" Modern Asian Studies 36, no. 01 (2002): 173-93. https://doi.org/10.1017/S0026749X02001051.\\",
  "Du Perron, Lalita, and Nicolas Magriel. \"Shellac, Bakelite, Vinyl, and Paper: Artifacts and Representations of North Indian Art Music.\" Oral Tradition 20, no. 1 (2005): 130-57. https://doi.org/10.1353/ort.2005.0012.\\",
  "Dudrah, Rajinder K. \"Drum'n'dhol 1: British Bhangra Music and Diasporic South Asian Identity Formation.\" European Journal of Cultural Studies 5, no. 3 (2002): 363-83.\\",
  "Dudrah, Rajinder K. \"Drum'n'dhol 1: British Bhangra Music and Diasporic South Asian Identity Formation.\" European Journal of Cultural Studies 5, no. 3 (2002): 363-83.\\",
  "Duggal, Vebhuti. \"Imagining Sound through the Pharmaish: Radios and Request-Postcards in North India, c. 1955-1975.\" BioScope: South Asian Screen Studies 9, no. 1 (2018): 1-23. https://doi.org/10.1177/0974927618767270.\\",
  "Durga, SAK. \"Western Influence on Indian Music-Nottuswara Sahithya of Muthuswami Dikshitar: An Intercultural Musical Form.\" Indian Musicological Society. Journal of the Indian Musicological Society 41 (2011): 31.\\",
  "Eisenberg, Andrew J. \"The Swahili Art of Indian Taarab: A Poetics of Vocality and Ethnicity on the Kenyan Coast.\" Comparative Studies of South Asia, Africa and the Middle East 37, no. 2 (2017): 336-54. http://muse.jhu.edu/article/667614.\\",
  "Farrell, Gerry, and Neil Sorrell. \"Colonialism, Philology, and Musical Ethnography in Nineteenth-Century India: The Case of S. W. Fallon.\" Music & Letters 88, no. 1 (2007): 107-20. JSTOR. http://www.jstor.org/stable/4140354.\\",
  "Fiol, Stefan. \"Articulating Regionalism through Popular Music: The Case of Nauchami Narayana in the Uttarakhand Himalayas.\" The Journal of Asian Studies 71, no. 2 (2012): 447-73.\\",
  "Ganti, Tejaswini. \"No Longer a Frivolous Singing and Dancing Nation of Movie-Makers: The Hindi Film Industry and Its Quest for Global Distinction.\" Visual Anthropology 25, no. 4 (2012): 340-65. https://doi.org/10.1080/08949468.2012.688473.\\",
  "Gehlawat, Ajay, and Rajinder Dudrah. \"The Evolution of Song and Dance in Hindi Cinema.\" South Asian Popular Culture 15, nos. 2-3 (2017): 103-8. https://doi.org/10.1080/14746689.2017.1407547.\\",
  "Gopinath, Gayatri. \"'Bombay, UK, Yuba City': Bhangra Music and the Engendering of Diaspora.\" Diaspora: A Journal of Transnational Studies 4, no. 3 (1995): 303-21.\\",
  "Greene, Paul. \"Nepal's 'Lok Pop' Music: Representations of the Folk, Tropes of Memory, and Studio Technologies.\" Asian Music 34, no. 1 (2003): 43.\\",
  "Greene, Paul. \"Sound Engineering in a Tamil Village: Playing Audio Cassettes as Devotional Performance.\" Ethnomusicology 43, no. 3 (1999): 459.\\",
  "Greene, Paul. \"The Dhamma as Sonic Praxis: Paritta Chant in Burmese Theravada Buddhism.\" Asian Music: Journal of the Society for Asian Music. 35, no. 2 (2004): 43.\\",
  "Groesbeck, Rolf. \"' Classical Music,'\" Folk Music,\" and the Brahmanical Temple in Kerala, India.\" Asian Music 30, no. 2 (1999): 87-112.\\",
  "Groesbeck, Rolf. \"Cultural Constructions of Improvisation in Tyampaka, a Genre of Temple Instrumental Music in Kerala, India.\" Ethnomusicology, JSTOR, 1999, 1-30.\\",
  "Hancock, Mary. \"Hindu Culture for an Indian Nation: Gender, Politics, and Elite Identity in Urban South India.\" American Ethnologist 22, no. 4 (1995): 907-26.\\",
  "Hansen, Kathryn. \"Making Women Visible: Gender and Race Cross-Dressing in the Parsi Theatre.\" Theatre Journal 51, no. 2 (1999): 127-47. http://muse.jhu.edu/journals/theatre_journal/v051/51.2hansen.html.\\",
  "Hartnett, Gerald. \"Cassette Culture, by Peter Manuel.\" Leonardo Music Journal 5, no. 1 (1995): 75-76. https://muse.jhu.edu/article/585333/summary.\\",
  "Higgins, Jon. \"From Prince to Populace: Patronage as a Determinant of Change in South Indian (Karnatak) Music.\" Asian Music 7, no. 2 (1976): 20.\\",
  "Hoerburger, Felix. \"Folk Music in the Caste System of Nepal.\" Yearbook of the International Folk Music Council 2 (1970): 142-47.\\",
  "Hoerburger, Felix. \"Folk Music in the Caste System of Nepal.\" Yearbook of the International Folk Music Council 2 (1970): 142-47.\\",
  "Hornabrook, Jasmine. \"Becoming One Again\": Music and Transnationalism in London's Sri Lankan Tamil Diaspora. Goldsmiths, University of London, 2016.\\",
  "Hornabrook, Jasmine. \"Becoming One Again\": Music and Transnationalism in London's Sri Lankan Tamil Diaspora. Goldsmiths, University of London, 2016.\\",
  "Hornabrook, Jasmine. \"Becoming One Again\": Music and Transnationalism in London's Sri Lankan Tamil Diaspora. Goldsmiths, University of London, 2016.\\",
  "Hornabrook, Jasmine. \"Song, Narrative, Belonging.\" Diasporic Inquiries into South Asian Women's Narratives: Alien Domiciles, Lexington Books, 2020, 179.\\",
  "Hornabrook, Jasmine. \"Songs of the Saints: Song Paths and Pilgrimage in London's Tamil Hindu Diaspora.\" Asian Music 49, no. 2 (2018): 106-50.\\",
  "Hughes, Stephen. \"The 'Music Boom' in Tamil South India: Gramophone, Radio and the Making of Mass Culture.\" Historical Journal of Film, Radio and Television 22, no. 4 (2002): 445-73.\\",
  "Jhingan, Shikha. \"Lata Mangeshkar's Voice in the Age of Cassette Reproduction.\" BioScope: South Asian Screen Studies 4, no. 2 (2013): 97-114. https://doi.org/10.1177/0974927613503232.\\",
  "Jhingan, Shikha. \"Re-Embodying the 'Classical.'\" BioScope: South Asian Screen Studies 2, no. 2 (2011): 157-79.\\",
  "Katz. \"Institutional Communalism in North Indian Classical Music.\" Ethnomusicology 56, no. 2 (2012): 279-98. https://doi.org/10.5406/ethnomusicology.56.2.0279.\\",
  "KUNREUTHER, LAURA. \"Between Love and Property: Voice, Sentiment, and Subjectivity in the Reform of Daughter's Inheritance in Nepal.\" American Ethnologist (Malden, USA) 36, no. 3 (2009): 545-62. https://doi.org/10.1111/j.1548-1425.2009.01178.x.\\",
  "KUNREUTHER, LAURA. \"SOUNDS OF DEMOCRACY: Performance, Protest, and Political Subjectivity.\" Cultural Anthropology (Washington) 33, no. 1 (2018): 1-31. https://doi.org/10.14506/ca33.1.01.\\",
  "Kunreuther, Laura. \"Technologies of the Voice: FM Radio, Telephone, and the Nepali Diaspora in Kathmandu.\" Cultural Anthropology 21, no. 3 (2006): 323-53. http://www.jstor.org.proxy.library.cornell.edu/stable/3805128.\\",
  "Kunreuther, Laura. \"Technologies of the Voice: FM Radio, Telephone, and the Nepali Diaspora in Kathmandu.\" Cultural Anthropology (Oxford, UK) 21, no. 3 (2006): 323-53. https://doi.org/10.1525/can.2006.21.3.323.\\",
  "Kunreuther, Laura. \"Transparent Media: Radio, Voice, and Ideologies of Directness in Postdemocratic Nepal.\" Journal of Linguistic Anthropology (Malden, USA) 20, no. 2 (2010): 334-51. https://doi.org/10.1111/j.1548-1395.2010.01073.x.\\",
  "Larkin, Brian. \"Indian Films and Nigerian Lovers: Media and the Creation of Parallel Modernities.\" Africa (Edinburgh University Press) 67, no. 3 (1997): 406.\\",
  "Leante, Laura. \"Shaping Diasporic Sounds: Identity as Meaning in Bhangra.\" The World of Music 52, no. 1/3 (2010): 229-52. http://www.jstor.org/stable/41700033.\\",
  "MacIszewski, Amelia. \"Multiple Voices, Multiple Selves: Song Style and North Indian Women's Identity.\" Asian Music 32, no. 2 (2001): 1.\\",
  "Magriel, Nicolas. \"Visualising North Indian Music: Looking at Khyl Songs.\" Worldofmusic The World of Music 47, no. 2 (2005): 119-36.\\",
  "Manuel, Peter. \"North Indian Sufi Popular Music in the Age of Hindu and Muslim Fundamentalism.\" Ethnomusicology 52, no. 3 (2008): 378-400. http://www.jstor.org/stable/20174605.\\",
  "Manuel, Peter. \"The Regional North Indian Popular Music Industry in 2014: From Cassette Culture to Cyberculture.\" Popular Music 33, no. 03 (2014): 389-412. https://doi.org/10.1017/S0261143014000592.\\",
  "Manuel, Peter, and Brian Bond. \"Rgs of Western India and Sindh.\" Analytical Approaches to World Music 10, no. 2 (2022). https://journal.iftawm.org/previous/2022-volume-10-no-2/manuel_bond/.\\",
  "Marshall, Wayne, and Jayson Beaster-Jones. \"It Takes a Little Lawsuit: The Flowering Garden of Bollywood Exoticism in the Age of Its Technological Reproducibility.\" South Asian Popular Culture South Asian Popular Culture 10, no. 3 (2012): 249-60.\\",
  "Miller, Flagg. \"Of Songs and Signs: Audiocassette Poetry, Moral Character, and the Culture of Circulation in Yemen.\" American Ethnologist 32, no. 1 (2005): 82.\\",
  "Morcom, Anna. \"An Understanding between Bollywood and Hollywood? The Meaning of Hollywoodstyle Music in Hindi Films.\" British Journal of Ethnomusicology 10, no. 1 (2001): 63-84.\\",
  "Morcom, Anna. \"An Understanding between Bollywood and Hollywood? The Meaning of Hollywoodstyle Music in Hindi Films.\" British Journal of Ethnomusicology 10, no. 1 (2001): 63-84.\\",
  "Morcom, Anna. \"An Understanding between Bollywood and Hollywood? The Meaning of Hollywoodstyle Music in Hindi Films.\" British Journal of Ethnomusicology 10, no. 1 (2001): 63-84.\\",
  "Muhammad, Ali, Jehangir Zeb Khan, Syed Imad Shah, and Murad Ali. \"Exploring Challenges and Opportunities of the New Social Entrepreneurs: The Case of Indigenous Musicpreneurs in KP Pakistan.\" Journal of Entrepreneurship in Emerging Economies, Emerald Publishing Limited, 2020.\\",
  "Mukherjee, Kamalini. \"Bangla Rock: Exploring the Counterculture and Dissidence in Post-Colonial Bengali Popular Music.\" International Journal of Pedagogy, Innovation and New Technologies 4 (2017): 35-47.\\",
  "Mukherjee, Kamalini. \"Bangla Rock: Exploring the Counterculture and Dissidence in Post-Colonial Bengali Popular Music.\" International Journal of Pedagogy, Innovation and New Technologies 4 (2017): 35-47.\\",
  "Murthy, Dhiraj. \"Representing South Asian Alterity? East London's Asian Electronic Music Scene and the Articulation of Globally Mediated Identities.\" European Journal of Cultural Studies 12, no. 3 (2009): 329-48.\\",
  "Nakassis, Constantine V., and Melanie A. Dean. \"Desire, Youth, and Realism in Tamil Cinema.\" Journal of Linguistic Anthropology 17, no. 1 (2007): 77-104. https://doi.org/10.1525/jlin.2007.17.1.77.\\",
  "Nakassis, Constantine V., and Amanda Weidman. \"Vision, Voice, and Cinematic Presence.\" Differences 29, no. 3 (2018): 107-36. https://doi.org/10.1215/10407391-7266494.\\",
  "Napier, John. \"Novelty That Must Be Subtle: Continuity, Innovation and 'Improvisation'in North Indian Music.\" Critical Studies in Improvisation 1, no. 3 (2006): 1-17.\\",
  "Napier, John. \"The Distribution of Authority in the Performance of North Indian Vocal Music.\" Ethnomusicology Forum 16, no. 2 (2007): 271-301.\\",
  "Narayan, Kirin, and Peter Manuel. \"Cassette Culture: Popular Music and Technology in North India.\" Yearbook for Traditional Music 27 (1995): 145. https://doi.org/10.2307/768113.\\",
  "Narayanan, Jayakrishnan, and Dhanavel Senkamalam Periyasamy. \"The Musical Language of Piety: The Semiotics of Visual Media in Shaping the Divine Status of Karnatik Music.\" Quarterly Review of Film and Video 38, no. 8 (2021): 747-65. https://doi.org/10.1080/10509208.2020.1796180.\\",
  "Nettl, Bruno. \"Contemplating the Concept of Improvisation and Its History in Scholarship.\" Music Theory Online 19, no. 2 (2013): 1-4.\\",
  "Neuman. \"Pedagogy, Practice, and Embodied Creativity in Hindustani Music.\" Ethnomusicology 56, no. 3 (2012): 426-49. https://doi.org/10.5406/ethnomusicology.56.3.0426.\\",
  "Neuman, Daniel M. \"A Khandani Perspective: Room for a (Long) View.\" MUSICULTURES 44, no. 1 (2017).\\",
  "Neuman, Daniel M. \"Indian Music as a Cultural System.\" Asian Music 17, no. 1 (1985): 98-113. ocn728988424. http://www.jstor.org/stable/833743.\\",
  "Neuman, Daniel M. \"Journey to the West.\" Indian Classical Music in North America. Contributions to Asian Studies 12 (1978): 40-55.\\",
  "Neuman, Daniel M. \"Master of the Srang, a Recording of Pandit Ram Narayan (Sarangi) with Suresh Talwalkar (Tabla).\" University Of Texas Press 11, no. 1 (1979): 121-23. https://doi.org/10.2307/833975.\\",
  "Neuman, Daniel M. Raga Purya Kalyan (Recording). 28, no. 2 (1984): 367-69. https://doi.org/10.2307/850780.\\",
  "Neuman, Daniel M. \"Saraswati's Changing Sound: An Anthropological Look at the Socio-Psychological Dynamics of Hindustani Music.\" Sangeet Natak 34 (1974): 81-86.\\",
  "Neuman, Daniel M. \"Sufi Music of India and Pakistan: Sound, Context and Meaning in Qawwali. By Regula Burckhardt Qureshi. Cambridge: Cambridge University Press, 1995. Cambridge Studies in Ethnomusicology. Xviii, 281 Pp. $24.95 (Paper).\" The Journal of Asian Studies 54, no. 03 (1995): 885-87.\\",
  "Neuman, Daniel M. \"The Ecology of Indian Music in North America.\" Bansuri 1 (1984).\\",
  "Neuman, Daniel M. \"The Social Organization of a Music Tradition: Hereditary Specialists in North India.\" Ethnomusicology 21, no. 2 (1977): 233-45.\\",
  "Neuman, Daniel M. \"Towards an Ethnomusicology of Culture Change in Asia.\" Asian Music 7, no. 2 (1976): 1-5. http://www.jstor.org/stable/833785.\\",
  "Neuman, Dard. \"Pedagogy, Practice, and Embodied Creativity in Hindustani Music.\" Ethnomusicology 56, no. 3 (2012): 426-49.\\",
  "Nijhawan, Amita. \"Excusing the Female Dancer: Tradition and Transgression in Bollywood Dancing.\" South Asian Popular Culture 7, no. 2 (2009): 99-112.\\",
  "Nooshin, Laudan, and Richard Widdess. \"Improvisation in Iranian and Indian Music.\" Journal of the Indian Musicological Society 36 (2006): 104-19.\\",
  "Nooshin, Laudan, and Richard Widdess. \"Improvisation in Iranian and Indian Music.\" Journal of the Indian Musicological Society 36 (2006): 104-19.\\",
  "Paige, Aaron. \"Illicit Worlds of Indian Dance: Cultures of Exclusion by Anna Morcom.\" Asian Music 48, no. 2 (2017): 150-54.\\",
  "Paik, Shailaja. \"Mangala Bansode and the Social Life of Tamasha: Caste, Sexuality, and Discrimination in Modern Maharashtra.\" Biography 40, no. 1 (2017): 170-98. https://doi.org/10.1353/bio.2017.0008.\\",
  "Paik, Shailaja. \"Mangala Bansode and the Social Life of Tamasha: Caste, Sexuality, and Discrimination in Modern Maharashtra.\" Biography 40, no. 1 (2017): 170-98. https://doi.org/10.1353/bio.2017.0008.\\",
  "Parthasarathy, TS. \"Contemporaries and Disciples of Sri Muthuswami Dikshitar.\" Journal of the Indian Musicological Society 6, no. 3 (1975): 28.\\",
  "Peiris, Eshantha. \"Changing Conceptualizations of Rhythm in Sri Lankan Up-Country Percussion Music: From Rhythmic Contours to Metric Cycles.\" Analytical Approaches to World Music 6, no. 2 (2018): 1-31.\\",
  "Peiris, Eshantha. The G\\'e4a Beraya Drumming Tradition of Sri Lanka. University of British Columbia, 2020.\\",
  "Peterson, Indira. \"Multilingual Dramas at the Tanjavur Maratha Court and Literary Cultures in Early Modern South India.\" The Medieval History Journal 14, no. 2 (2011): 285-321.\\",
  "Powers, Harold. \"A Canonical Museum of Imaginary Music.\" Current Musicology, Department of Music, Columbia University, 1996, 5-25.\\",
  "Powers, Harold. \"A Canonical Museum of Imaginary Music.\" Current Musicology, Department of Music, Columbia University, 1996, 5-25.\\",
  "Powers, Harold S. \"Mode and Raga.\" The Musical Quarterly 44, no. 4 (1958): 448-60.\\",
  "Quader, Shams Bin, and Guy Redden. \"Approaching the Underground: The Production of Alternatives in the Bangladeshi Metal Scene.\" Cultural Studies 29, no. 3 (2015): 401-24.\\",
  "Quader, Shams Bin, and Guy Redden. \"Approaching the Underground: The Production of Alternatives in the Bangladeshi Metal Scene.\" Cultural Studies 29, no. 3 (2015): 401-24.\\",
  "Qureshi, Regula. \"Confronting the Social: Mode of Production and the Sublime for (Indian) Art Music.\" Ethnomusicology 44, no. 1 (2000): 15.\\",
  "Qureshi, Regula. \"Exploring Time Cross-Culturally: Ideology and Performance of Time in the Sufi Qawwl.\" Journal of Musicology 12, no. 4 (1994): 491.\\",
  "Qureshi, Regula. \"His Master's Voice? Exploring Qawwali and 'Gramophone Culture' in South Asia.\" Popular Music 18, no. 1 (1999): 63.\\",
  "Qureshi, Regula. \"How Does Music Mean? Embodied Memories and the Politics of Affect in the Indian 'Sarangi.'\" American Ethnologist 27, no. 4 (2000): 805.\\",
  "Qureshi, Regula. \"How Does Music Mean? Embodied Memories and the Politics of Affect in the Indian Sarangi.\" American Ethnologist 27, no. 4 (2000): 805-38.\\",
  "Qureshi, Regula. \"Indo-Muslim Religious Music, an Overview.\" Asian Music 3, no. 2 (1972): 15.\\",
  "Qureshi, Regula. \"Islamic Music in an Indian Environment: The Shi'a Majlis.\" Ethnomusicology 25, no. 1 (1981): 41.\\",
  "Qureshi, Regula. \"Musical Gesture and Extra-Musical Meaning: Words and Music in the Urdu Ghazal.\" Journal of the American Musicological Society 43, no. 3 (1990): 457.\\",
  "Qureshi, Regula. \"Musical Sound and Contextual Input: A Performance Model for Musical Analysis.\" Ethnomusicology 31, no. 1 (1987): 56.\\",
  "Qureshi, Regula. \"'Muslim Devotional': Popular Religious Music and Muslim Identity under British, Indian and Pakistani Hegemony.\" Asian Music 24, no. 1 (1992): 111. https://doi.org/10.2307/834453.\\",
  "Qureshi, Regula. \"'Muslim Devotional': Popular Religious Music and Muslim Identity under British, Indian and Pakistani Hegemony.\" Asian Music 24, no. 1 (1993): 111.\\",
  "Qureshi, Regula. \"Tarannum: The Chanting of Urdu Poetry.\" Ethnomusicology 13, no. 3 (1969): 425.\\",
  "Qureshi, Regula Burckhardt. \"Confronting the Social: Mode of Production and the Sublime for (Indian) Art Music.\" Ethnomusicology 44, no. 1 (2000): 15. https://doi.org/10.2307/852653.\\",
  "Qureshi, Regula Burckhardt. \"Confronting the Social: Mode of Production and the Sublime for (Indian) Art Music.\" Ethnomusicology 44, no. 1 (2000): 15. https://doi.org/10.2307/852653.\\",
  "Qureshi, Regula Burckhardt. \"Confronting the Social: Mode of Production and the Sublime for (Indian) Art Music.\" Ethnomusicology 44, no. 1 (2000): 15-38.\\",
  "Qureshi, Regula Burckhardt. \"His Master's Voice? Exploring Qawwali and 'Gramophone Culture'in South Asia 1.\" Popular Music 18, no. 1 (1999): 63-98. https://www.cambridge.org/core/journals/popular-music/article/his-masters-voice-exploring-qawwali-and-gramophone-culture-in-south-asia-1/735F65C9316CDBD55883C7293062CAD3.\\",
  "Qureshi, Regula Burckhardt. \"In Search of Begum Akhtar: Patriarchy, Poetry, and Twentieth-Century Indian Music.\" The World of Music 52, no. 1/3 (2010): 347-86. http://www.jstor.org/stable/41700039.\\",
  "Qureshi, Regula Burckhardt. \"Musical Gesture and Extra-Musical Meaning: Words and Music in the Urdu Ghazal.\" Journal of the American Musicological Society 43, no. 3 (1990): 457-97. https://doi.org/10.2307/831743.\\",
  "Qureshi, Regula Burckhardt. \"Musical Gesture and Extra-Musical Meaning: Words and Music in the Urdu Ghazal.\" Journal of the American Musicological Society 43, no. 3 (1990): 457-97. https://doi.org/10.2307/831743.\\",
  "Rabbani, Golam. Commodifying Baul Spirituality: Changing Baul Literature and Music in Bangladesh. Queen's University (Canada), 2021.\\",
  "Rajapandian, Radha, Bharathi Dhanapal, and Sivakumar Iyyanar. \"Representation of Caste and Class in Modern Tamil Films.\" American Journal of Economics and Sociology 80, no. 3 (2021): 915-29.\\",
  "Ram, Kalpana. \"Being 'Rasikas': The Affective Pleasures of Music and Dance Spectatorship and Nationhood in Indian Middle-Class Modernity.\" Journal of the Royal Anthropological Institute 17, no. s1 (2011). http://onlinelibrary.wiley.com/doi/10.1111/j.1467-9655.2011.01694.x/full.\\",
  "Ranganathan, Sumitra. Dwelling in My Voice: Tradition as Musical Judgment and Aesthetic Sense in North Indian Classical Dhrupad. n.d., 190.\\",
  "Rao, Shakuntala. \"'I Need an Indian Touch': Glocalization and Bollywood Films.\" Journal of International and Intercultural Communication 3, no. 1 (2010): 1-19.\\",
  "Rege, Sharmila. \"The Hegemonic Appropriation of Sexuality: The Case of the Lavani Performers of Maharashtra.\" Contributions to Indian Sociology 29, nos. 1-2 (1995): 23-38. https://doi.org/10.1177/0069966795029001003.\\",
  "Rege, Sharmila. \"The Hegemonic Appropriation of Sexuality: The Case of the Lavani Performers of Maharashtra.\" Contributions to Indian Sociology 29, nos. 1-2 (1995): 23-38. https://doi.org/10.1177/0069966795029001003.\\",
  "Rege, Sharmila. \"Understanding Popular Culture: The Satyashodhak and Ganesh Mela in Maharashtra - Sharmila Rege, 2000.\" Sociological Bulletin, March 8, 2017. http://journals.sagepub.com/doi/10.1177/0038022920000202?icid=int.sj-abstract.similar-articles.3.\\",
  "Roda, P. Allen. \"Tabla Tuning on the Workshop Stage: Toward a Materialist Musical Ethnography.\" Ethnomusicology Forum 23, no. 3 (2014): 360-82. https://doi.org/10.1080/17411912.2014.919871.\\",
  "Rohrmeier, Martin, and Richard Widdess. \"Incidental Learning of Melodic Structure of North Indian Music.\" Cognitive Science 41, no. 5 (2017): 1299-327.\\",
  "Ross, Israel J. \"Ritual and Music in South India: Syrian Christian Liturgical Music in Kerala.\" Asian Music 11, no. 1 (1979): 80-98.\\",
  "Roy, Jeff. \"The Internet Guru: Online Pedagogy in Indian Classical Music Traditions.\" Asian Music 47, no. 1 (2016): 103-35. http://www.jstor.org.ezproxy.cul.columbia.edu/stable/24913573.\\",
  "Rudisill, Kristen. \"Pritham Chakravarthy: Performing Aravanis' Life Stories.\" Asian Theatre Journal 32, no. 2 (2015): 536-55. https://doi.org/10.1353/atj.2015.0025.\\",
  "Sarrazin, Natalie. \"Celluloid Love Songs: Musical Modus Operandi and the Dramatic Aesthetics of Romantic Hindi Film.\" Popular Music 27, no. 3 (2008): 393-411.\\",
  "Sarrazin, Natalie. \"Celluloid Love Songs: Musical Modus Operandi and the Dramatic Aesthetics of Romantic Hindi Film.\" Popular Music 27, no. 3 (2008): 393-411.\\",
  "Schofield, Katherine Butler. \"Emotions in Indian Music History: Anxiety in Late Mughal Hindustan.\" South Asian History and Culture 12, nos. 2-3 (2021): 182-205. https://doi.org/10.1080/19472498.2021.1878792.\\",
  "Schofield, Katherine Butler. \"The Courtesan Tale: Female Musicians and Dancers in Mughal Historical Chronicles, c. 1556-1748.\" Gender & History 24, no. 1 (2012): 150-71.\\",
  "Shankaran, T. \"The Nagaswaram Tradition Systematised by Ramaswami Dikshitar.\" Journal of the Indian Musicological Society 6, no. 3 (1975): 16.\\",
  "Sherinian, Zoe. \"The Indigenization of Tamil Christian Music: Musical Style and Liberation Theology.\" The World of Music, JSTOR, 2005, 125-65.\\",
  "Shulman, David. \"The Buzz of God and the Click of Delight.\" Aesthetics in Performance: Formations of Symbolic Construction and Experience, Berghahn Books, 2005, 43-63.\\",
  "Skillman, Teri. \"The Bombay Hindi Film Song Genre: A Historical Survey.\" Yearbook for Traditional Music 18 (1986): 133-44. https://doi.org/10.2307/768525.\\",
  "Srivastava, Sanjay. \"Voice, Gender and Space in Time of Five-Year Plans: The Idea of Lata Mangeshkar.\" Economic and Political Weekly, 2004, 2019-28. http://www.jstor.org/stable/4415027.\\",
  "Stirr, Anna. \"Sounding and Writing a Nepali Public Sphere: The Music and Language of Jhyure.\" Asian Music 46, no. 1 (2015): 3-38.\\",
  "Sundar, Pavitra. \"Meri Awaaz Suno: Women, Vocality, and Nation in Hindi Cinema.\" Meridians: Feminism, Race, Transnationalism 8, no. 1 (2008): 144-79.\\",
  "Sykes, Jim. \"Culture as Freedom: Musical\" Liberation\" in Batticaloa, Sri Lanka.\" Ethnomusicology 57, no. 3 (2013): 485-517.\\",
  "Sykes, Jim. \"Culture as Freedom: Musical\" Liberation\" in Batticaloa, Sri Lanka.\" Ethnomusicology 57, no. 3 (2013): 485-517. http://www.jstor.org/stable/10.5406/ethnomusicology.57.3.0485.\\",
  "Sykes, Jim. Musical Knowledge and the Vernacular Past in Post-War Sri Lanka. 2012. http://sjdspace.sagepub.com/wp-content/uploads/2013/09/EBul-Sykes-July2012.pdf.\\",
  "Tallotte, William. \"Meaningful Adjustments:\\",
  "Musical Performance and Ritual Action in a South Indian Temple.\" Analytical Approaches to World Music 4, no. 1 (2015). http://iftawm.org/journal/oldsite/articles/2015a/Tallotte_AAWM_Vol_4_1.html.\\",
  "Terada, Yoshitaka. Multiple Interpretations of a Charismatic Individual: The Case of the Great Nagasvaram Musician, TN Rajarattinam Pillai. University of Washington, 1992.\\",
  "Terada, Yoshitaka. \"TN Rajarattinam Pillai and Caste Rivalry in South Indian Classical Music.\" Ethnomusicology 44, no. 3 (2000): 460-90.\\",
  "Urban, Hugh B. \"The Politics of Madness the Construction and Manipulation of the 'Baul' Image in Modern Bengal.\" South Asia: Journal of South Asian Studies 22, no. 1 (1999): 13-46. https://doi.org/10.1080/00856409908723358.\\",
  "V. Nakassis, Constantine. \"A Tamil-Speaking Heroine.\" BioScope: South Asian Screen Studies 6, no. 2 (2015): 165-86. https://doi.org/10.1177/0974927615600625.\\",
  "Van Der Linden, Bob. \"Pre-Twentieth-Century Sikh Sacred Music: The Mughals, Courtly Patronage and Canonisation.\" South Asia: Journal of South Asian Studies 38, no. 2 (2015): 141-55.\\",
  "Venkateswaran, Pramila. \"Performing Dalit Feminist Youth Activism in South India: Rap, Gaana, and Street Theater.\" Journal of International Women's Studies 24, no. 2 (2022): 12.\\",
  "Vijayakrishnan, KG. \"The Function and Scope of Notation in Carnatic Music.\" Indian Musicological Society. Journal of the Indian Musicological Society 40 (2009): 140.\\",
  "Virani, Vivek. \"From Satsag to Stage: Negotiating Aesthetic Theologies and Aspirational Subjectivities in a North Indian Bhajan Competition.\" Ethnomusicology 66, no. 1 (2022): 106-37.\\",
  "Viswanathan Peterson, Indira. \"The Evolution of the Kurava\\'f1cidance Drama in Tamil Nadu: Negotiating the'Folk'and the'Classical'in the Bhrata Ntyam Canon.\" South Asia Research 18, no. 1 (1998): 39-72.\\",
  "Weidman, Amanda. \"Anthropology and Voice.\" Annual Review of Anthropology 43, no. 1 (2014): 37-51. https://doi.org/10.1146/annurev-anthro-102313-030050.\\",
  "Weidman, Amanda. \"Neoliberal Logics of Voice: Playback Singing and Public Femaleness in South India.\" Culture, Theory and Critique 55, no. 2 (2014): 175-93. https://doi.org/10.1080/14735784.2014.899883.\\",
  "Weidman, Amanda. \"Neoliberal Logics of Voice: Playback Singing and Public Femaleness in South India.\" Culture, Theory and Critique 55, no. 2 (2014): 175-93. https://doi.org/10.1080/14735784.2014.899883.\\",
  "Weidman, Amanda. \"Neoliberal Logics of Voice: Playback Singing and Public Femaleness in South India.\" Culture, Theory and Critique 55, no. 2 (2014): 175-93. https://doi.org/10.1080/14735784.2014.899883.\\",
  "Weidman, Amanda. \"Neoliberal Logics of Voice: Playback Singing and Public Femaleness in South India.\" Culture, Theory and Critique, January 1, 2014, 175-93. http://repository.brynmawr.edu/anth_pubs/8.\\",
  "Widdess, Richard. \"Orality, Writing and Music in South Asia.\" Musicology Today: Journal of the National University of Music Bucharest 5, no. 19 (2014): 136-53.\\",
  "Wolf, Richard K. \"Embodiment and Ambivalence: Emotion in South Asian Muharram Drumming.\" Yearbook for Traditional Music 32 (2000): 81-116. JSTOR. https://doi.org/10.2307/3185244.\\",
  "Wolf, Richard Kent. \"Three Perspectives on Music and the Idea of Tribe in India.\" Asian Music 32, no. 1 (2000): 5-34. JSTOR. https://doi.org/10.2307/834329.\\",
  "Yuko, Eguchi. \"Re-Creating\" Inida\" through Ritual and Musical Practices in Pittsburgh, USA.\" Asian Musicology 12 (2008): 49-83.\\",
  "Zipp, Lena. \"Code-Switching in the Media: Identity Negotiations in a Gujarati Diaspora Radio Program.\" International Journal of the Sociology of Language 2017, no. 247 (2017): 33-48.\\",
  "Zuberi, Nabeel. \"Listening While Muslim.\" Popular Music 36, no. 1 (2017): 33-42. https://doi.org/10.1017/S0261143016000659.\\",
  "Zuberi, Nabeel. \"Listening While Muslim.\" Popular Music 36, no. 1 (2017): 33-42. https://doi.org/10.1017/S0261143016000659.\\"
];